
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WindowsXP
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox();
        l = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Login your profile from here !!!!!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 330, -1));

        jLabel2.setText("You are");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Supervisor", "Operator" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, -1));

        l.setText("User name");
        getContentPane().add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, 20));
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 140, -1));

        jLabel4.setText("    PIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, -1));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 60, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 70, -1));

        jButton4.setText(" Create new profile.Click here");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 230, -1));

        jButton5.setText("Forgot Yor PIN.Click Here");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 230, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture10.JPG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        pwd.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(t1.getText().length()!=0&&new String(pwd.getPassword()).length()!=0) 
{
    int i =cb1.getSelectedIndex();

        if(i==0){
        try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/billingcounter?zeroDateTimeBehavior=convertToNull","root", "123");
                Statement st=con.createStatement();
                ResultSet rs =st.executeQuery("Select * from admin where username='"+t1.getText()+"';");
                if(rs.next()){
                    String a=rs.getString("pin");
                    if(a.equals(new String(pwd.getPassword()))){
                        adminpro adminpro=new adminpro();
                        adminpro.setVisible(true);
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null,"Wrong Password");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Wrong Username");
                }
                
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }}
        if(i==1){
        try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/billingcounter?zeroDateTimeBehavior=convertToNull","root", "123");
                Statement st=con.createStatement();
                ResultSet rs =st.executeQuery("Select * from superwiser where sid='"+t1.getText()+"';");
                if(rs.next()){
                    String a=rs.getString("pin");
                    if(a.equals(new String(pwd.getPassword()))){
                        if(rs.getString("status").equals("online")){
                        superwiserpro superwiserpro=new superwiserpro();
                        superwiserpro.setVisible(true);
                        this.dispose();}else{
                            JOptionPane.showMessageDialog(null,"You Are BLOCKED");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Wrong Password");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Wrong ID");
                }
                
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }}
        if(i==2){
        try{
            Class.forName("java.sql.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/billingcounter?zeroDateTimeBehavior=convertToNull","root", "123");
                Statement st=con.createStatement();
                ResultSet rs =st.executeQuery("Select * from oprator where id='"+t1.getText()+"';");
                if(rs.next()){
                    String a=rs.getString("pin");
                    if(a.equals(new String(pwd.getPassword()))){
                        if(rs.getString("status").equals("online")){
                        opratorpro opratorpro=new opratorpro();
                        opratorpro.setVisible(true);}else{
                            JOptionPane.showMessageDialog(null,"You Are BLOCKED");
                        }
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null,"Wrong Password");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Wrong ID");
                }
                
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        }
}
else{
    JOptionPane.showMessageDialog(null, "All fields are mandatory");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        newprofile newprofile=new newprofile();
        newprofile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        if(cb1.getSelectedIndex()==0){
            l.setText("Username");
        }else{
            l.setText("ID");
        }
            
    }//GEN-LAST:event_cb1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int a=cb1.getSelectedIndex();
        if(a==0)
        {
            this.dispose();
            adminforgetpwd b= new adminforgetpwd();
            b.setVisible(true);
        }
        if(a==1)
        {
            this.dispose();
            supervisorforgetpwd c= new supervisorforgetpwd();
            c.setVisible(true);
        }
        if(a==2)
        {
            this.dispose();
            operatorforgetpwd d= new operatorforgetpwd();
            d.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
